commitPath: { color: colors.text, fontSize: 13, flexShrink: 1 },
  commitErr: { color: colors.danger, fontSize: 11 },
  liveRow: { flexDirection: "row", alignItems: "center", gap: 8, marginTop: space.sm },
  confirmWrap: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.6)",
    alignItems: "center",
    justifyContent: "center",
    padding: space.lg,
  },
  confirmCard: {
    width: "100%",
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: space.lg,
    alignItems: "center",
    gap: 10,
  },
  confirmTitle: { color: colors.text, fontSize: 18, fontWeight: "800" },
  confirmText: { color: colors.muted, fontSize: 14, textAlign: "center", lineHeight: 20 },
  confirmRow: { flexDirection: "row", gap: space.sm, marginTop: space.sm, width: "100%" },
  confirmBtn: { flex: 1, height: 48, borderRadius: radius.md, alignItems: "center", justifyContent: "center" },
  cancelBtn: { backgroundColor: colors.surface2, borderWidth: 1, borderColor: colors.border },
  delBtn: { backgroundColor: colors.danger },
  cancelText: { color: colors.text, fontWeight: "800", fontSize: 15 },
  delText: { color: "#fff", fontWeight: "800", fontSize: 15 },
  modelWrap: { flex: 1, backgroundColor: "rgba(0,0,0,0.55)" },
  modelSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radius.xl,
    borderTopRightRadius: radius.xl,
    padding: space.lg,
    paddingBottom: 40,
    borderTopWidth: 1,
    borderColor: colors.border,
  },
  mHandle: {
    width: 44,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.border,
    alignSelf: "center",
    marginBottom: space.md,
  },
  modelTitle: { color: colors.text, fontSize: 19, fontWeight: "800", marginBottom: space.sm },
  modelRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.surface2,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.md,
    padding: space.md,
    marginBottom: space.sm,
  },
  modelRowActive: { borderColor: colors.accent },
  modelLabel: { color: colors.text, fontSize: 15, fontWeight: "700" },
  modelHint: { color: colors.muted, fontSize: 12, marginTop: 2 },
});